using System;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using System.Linq;
using System.Collections.Generic;

public class MainForm : Form
{
    public static readonly string AppRoot = GetAppRoot();
    public static string GetAppRoot() { string[] paths = { Path.GetDirectoryName(Environment.ProcessPath), Directory.GetCurrentDirectory(), AppDomain.CurrentDomain.BaseDirectory, Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\")) }; foreach (string p in paths) { if (!string.IsNullOrWhiteSpace(p) && Directory.Exists(Path.Combine(p, "PBS"))) return p; } return Path.GetDirectoryName(Environment.ProcessPath); }

    // --- VARIABLES ---
    private TabControl tabMain, tabBagPockets, tabEditor;
    private TabPage tabParty, tabPC, tabBag;
    private PictureBox[] partySlots = new PictureBox[6], pcSlots = new PictureBox[30];
    private Label[] partyLabels = new Label[6];
    private ComboBox cbBoxSelector, cbBagItems, cbNature, cbAbility, cbItem, cbGender;
    private Button btnPrevBox, btnNextBox, btnAddPokemon, btnBagAdd, btnBagRemove, btnInfo, btnLoad, btnSave, btnDescAbility, btnChangeFormInEditor, btnMaxPP;
    private ContextMenuStrip pokeMenu;
    private DataGridView[] dgvPockets = new DataGridView[9]; 
    private NumericUpDown numBagQty, numMoney, numLevel;
    
    private GroupBox grpEditor;
    private PictureBox picSprite;
    private CheckBox chkShiny, chkSuperShiny; 
    private Label lblStatus;
    private TextBox txtNickname;
    private NumericUpDown[] numIVs = new NumericUpDown[6], numEVs = new NumericUpDown[6], numPPs = new NumericUpDown[4], numPPUps = new NumericUpDown[4];
    private Label[] lblStatNames = new Label[6]; 
    private string[] statNames = { "PS", "Ataque", "Defensa", "At. Esp", "Def. Esp", "Velocidad" };
    private ComboBox[] cbMoves = new ComboBox[4];
    private Button[] btnDescMoves = new Button[4];

    // --- LÓGICA ---
    private PBSReader pbs;
    private SaveDataModel currentSaveData;
    private string currentSavePath;
    private bool isEditingParty = true, isUpdatingUI = false, isDragging = false;
    private int currentBoxIndex = 0, currentSlotIndex = -1, dragSlotIndex = -1;
    private Point dragStartPos;
    private DateTime lastBoxSwitch = DateTime.MinValue;
    private class DragData { public bool IsParty; public int BoxIndex; public int SlotIndex; }
    private readonly string[] PocketNames = { "", "Objetos", "Medicinas", "Poké Balls", "MTs y MOs", "Bayas", "Mega Piedras", "Batalla", "Clave" };

    public MainForm()
    {
        this.Text = "AñilHeX - Editor Maestro"; this.Size = new Size(840, 600); this.FormBorderStyle = FormBorderStyle.FixedSingle; this.MaximizeBox = false; this.StartPosition = FormStartPosition.CenterScreen; this.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        InitializeUI();
        pbs = new PBSReader(); string pbsPath = Path.Combine(AppRoot, "PBS"); if (Directory.Exists(pbsPath)) pbs.LoadPBSDirectory(pbsPath);
    }

    private void InitializeUI()
    {
        btnLoad = new Button { Text = "Abrir Partida...", Location = new Point(12, 10), Size = new Size(120, 30) }; btnLoad.Click += BtnLoad_Click; this.Controls.Add(btnLoad);
        btnSave = new Button { Text = "Guardar Cambios", Location = new Point(140, 10), Size = new Size(120, 30), Enabled = false, BackColor = Color.LightBlue }; btnSave.Click += BtnSave_Click; this.Controls.Add(btnSave);

        tabMain = new TabControl { Location = new Point(12, 50), Size = new Size(390, 490), AllowDrop = true };
        tabMain.SelectedIndexChanged += (s, e) => { if (tabMain.SelectedTab == tabBag) UpdateBagItemDropdown(); };
        tabMain.DragOver += (s, e) => { Point pt = tabMain.PointToClient(new Point(e.X, e.Y)); for (int i = 0; i < tabMain.TabPages.Count; i++) { if (tabMain.GetTabRect(i).Contains(pt)) { if (tabMain.SelectedIndex != i) tabMain.SelectedIndex = i; return; } } };
        
        // --- EQUIPO ---
        tabParty = new TabPage("Equipo"); tabParty.AllowDrop = true;
        pokeMenu = new ContextMenuStrip(); pokeMenu.Items.Add("Mover al Equipo / PC").Click += MovePokemonQuick_Click; pokeMenu.Items.Add("Cambiar Forma / Paradox").Click += ChangeForm_Click; pokeMenu.Items.Add("Eliminar Pokémon").Click += DeletePokemon_Click;
        pokeMenu.Opening += (s, e) => { var pb = (s as ContextMenuStrip).SourceControl as PictureBox; if (pb == null || currentSaveData == null) { e.Cancel = true; return; } bool isParty = pb.Parent == tabParty; int slot = (int)pb.Tag; Pokemon p = isParty ? (slot < currentSaveData.Party.Count ? currentSaveData.Party[slot] : null) : currentSaveData.Boxes[currentBoxIndex].Slots[slot]; if (p == null) { e.Cancel = true; return; } pokeMenu.Items[0].Text = isParty ? "Enviar a la Caja del PC" : "Enviar al Equipo"; pokeMenu.Items[1].Visible = FormDatabase.HasFormsOrParadox(p.InternalSpecies, AppRoot); };

        for (int i = 0; i < 6; i++) {
            int col = i % 2, row = i / 2, px = 20 + (col * 180), py = 20 + (row * 100);
            partySlots[i] = new PictureBox { Location = new Point(px, py), Size = new Size(64, 64), BorderStyle = BorderStyle.FixedSingle, SizeMode = PictureBoxSizeMode.CenterImage, Cursor = Cursors.Hand, Tag = i, AllowDrop = true, ContextMenuStrip = pokeMenu, BackColor = Color.WhiteSmoke }; partySlots[i].MouseDown += UniversalSlot_MouseDown; partySlots[i].MouseMove += UniversalSlot_MouseMove; partySlots[i].MouseUp += UniversalSlot_MouseUp; partySlots[i].DragEnter += UniversalSlot_DragEnter; partySlots[i].DragDrop += PartySlot_DragDrop; partySlots[i].Click += PartySlot_ClickAction; 
            partyLabels[i] = new Label { Location = new Point(px + 70, py + 15), Size = new Size(100, 40), TextAlign = ContentAlignment.MiddleLeft, Font = new Font("Segoe UI", 9.5F, FontStyle.Bold), Text = "Vacío", ForeColor = Color.Gray };
            tabParty.Controls.Add(partySlots[i]); tabParty.Controls.Add(partyLabels[i]);
        }
        tabMain.TabPages.Add(tabParty);
        
        // --- PC ---
        tabPC = new TabPage("Cajas PC"); tabPC.AllowDrop = true;
        btnPrevBox = new Button { Text = "<", Location = new Point(5, 10), Size = new Size(25, 25), AllowDrop = true }; btnPrevBox.Click += (s, e) => { if (cbBoxSelector.SelectedIndex > 0) cbBoxSelector.SelectedIndex--; }; btnPrevBox.DragOver += BtnBoxChange_DragOver; tabPC.Controls.Add(btnPrevBox);
        cbBoxSelector = new ComboBox { Location = new Point(35, 10), Size = new Size(215, 25), DropDownStyle = ComboBoxStyle.DropDownList }; cbBoxSelector.SelectedIndexChanged += CbBoxSelector_SelectedIndexChanged; tabPC.Controls.Add(cbBoxSelector);
        btnNextBox = new Button { Text = ">", Location = new Point(255, 10), Size = new Size(25, 25), AllowDrop = true }; btnNextBox.Click += (s, e) => { if (cbBoxSelector.SelectedIndex < cbBoxSelector.Items.Count - 1) cbBoxSelector.SelectedIndex++; }; btnNextBox.DragOver += BtnBoxChange_DragOver; tabPC.Controls.Add(btnNextBox);
        btnAddPokemon = new Button { Text = "+ Añadir", Location = new Point(285, 9), Size = new Size(75, 27) }; btnAddPokemon.Click += BtnAddPokemon_Click; tabPC.Controls.Add(btnAddPokemon);
        for (int i = 0; i < 30; i++) { int col = i % 6, row = i / 6; pcSlots[i] = new PictureBox { Location = new Point(10 + (col * 58), 50 + (row * 58)), Size = new Size(54, 54), BorderStyle = BorderStyle.FixedSingle, SizeMode = PictureBoxSizeMode.CenterImage, Cursor = Cursors.Hand, Tag = i, AllowDrop = true, ContextMenuStrip = pokeMenu }; pcSlots[i].MouseDown += UniversalSlot_MouseDown; pcSlots[i].MouseMove += UniversalSlot_MouseMove; pcSlots[i].MouseUp += UniversalSlot_MouseUp; pcSlots[i].DragEnter += UniversalSlot_DragEnter; pcSlots[i].DragDrop += PcSlot_DragDrop; pcSlots[i].Click += PcSlot_ClickAction; tabPC.Controls.Add(pcSlots[i]); }
        tabMain.TabPages.Add(tabPC);

        // --- MOCHILA ---
        tabBag = new TabPage("Mochila"); tabBagPockets = new TabControl { Location = new Point(5, 5), Size = new Size(370, 290) }; tabBagPockets.SelectedIndexChanged += (s, e) => UpdateBagItemDropdown();
        for (int pId = 1; pId <= 8; pId++) { TabPage pTab = new TabPage(PocketNames[pId]); dgvPockets[pId] = new DataGridView { Dock = DockStyle.Fill, AllowUserToAddRows = false, AllowUserToDeleteRows = true, RowHeadersVisible = false, AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill, SelectionMode = DataGridViewSelectionMode.FullRowSelect, AllowUserToResizeRows = false, AllowUserToResizeColumns = false }; dgvPockets[pId].Columns.Add("InternalName", "ID"); dgvPockets[pId].Columns["InternalName"].Visible = false; dgvPockets[pId].Columns.Add("Name", "Objeto"); dgvPockets[pId].Columns["Name"].ReadOnly = true; dgvPockets[pId].Columns.Add("Quantity", "Cant."); dgvPockets[pId].Columns["Quantity"].Width = 60; if (pId == 4 || pId == 8) { dgvPockets[pId].Columns["Quantity"].ReadOnly = true; dgvPockets[pId].Columns["Quantity"].DefaultCellStyle.BackColor = Color.WhiteSmoke; } dgvPockets[pId].RowsRemoved += (s, e) => UpdateBagItemDropdown(); pTab.Controls.Add(dgvPockets[pId]); tabBagPockets.TabPages.Add(pTab); }
        tabBag.Controls.Add(tabBagPockets);
        cbBagItems = new ComboBox { Location = new Point(5, 301), Size = new Size(160, 25), AutoCompleteMode = AutoCompleteMode.SuggestAppend, AutoCompleteSource = AutoCompleteSource.ListItems }; cbBagItems.TextUpdate += (s, e) => { if (cbBagItems.DroppedDown) cbBagItems.DroppedDown = false; }; tabBag.Controls.Add(cbBagItems);
        numBagQty = new NumericUpDown { Location = new Point(170, 301), Size = new Size(55, 25), Minimum = 1, Maximum = 999, Value = 1 }; tabBag.Controls.Add(numBagQty);
        btnBagAdd = new Button { Location = new Point(230, 300), Size = new Size(60, 27), Text = "Añadir", BackColor = Color.LightGreen }; btnBagAdd.Click += BtnBagAdd_Click; tabBag.Controls.Add(btnBagAdd);
        Button btnBagMaxSelected = new Button { Location = new Point(295, 300), Size = new Size(75, 27), Text = "+ Max Sel.", BackColor = Color.LightGreen }; btnBagMaxSelected.Click += BtnBagMaxSelected_Click; tabBag.Controls.Add(btnBagMaxSelected);
        Button btnBagMaxCurrent = new Button { Location = new Point(5, 332), Size = new Size(160, 27), Text = "Max 999 a mis Objetos", BackColor = Color.LightSkyBlue }; btnBagMaxCurrent.Click += BtnBagMaxCurrent_Click; tabBag.Controls.Add(btnBagMaxCurrent);
        Button btnBagAddAll = new Button { Location = new Point(170, 332), Size = new Size(200, 27), Text = "Inyectar Todos los del Juego", BackColor = Color.Plum }; btnBagAddAll.Click += BtnBagAddAll_Click; tabBag.Controls.Add(btnBagAddAll);
        btnBagRemove = new Button { Location = new Point(5, 364), Size = new Size(365, 27), Text = "Borrar Objeto Seleccionado", BackColor = Color.LightCoral }; btnBagRemove.Click += BtnBagRemove_Click; tabBag.Controls.Add(btnBagRemove);
        
        // --- DINERO EN MOCHILA ---
        Label lblMoney = new Label { Text = "Dinero en Billetera:", Location = new Point(5, 415), AutoSize = true, Font = new Font("Segoe UI", 10.5F, FontStyle.Bold), ForeColor = Color.DarkSlateGray };
        numMoney = new NumericUpDown { Location = new Point(155, 413), Size = new Size(140, 25), Minimum = 0, Maximum = 9999999999m, ThousandsSeparator = true, Font = new Font("Segoe UI", 10.5F, FontStyle.Bold) };
        tabBag.Controls.Add(lblMoney);
        tabBag.Controls.Add(numMoney);

        tabMain.TabPages.Add(tabBag);
        this.Controls.Add(tabMain);

        // --- EDITOR POKEMON ---
        grpEditor = new GroupBox { Text = "Editor de Pokémon", Location = new Point(415, 50), Size = new Size(395, 480), Enabled = false };
        picSprite = new PictureBox { Location = new Point(20, 20), Size = new Size(68, 56), SizeMode = PictureBoxSizeMode.Zoom, BorderStyle = BorderStyle.FixedSingle, Cursor = Cursors.Hand }; picSprite.Click += (s, e) => { chkShiny.Checked = !chkShiny.Checked; }; grpEditor.Controls.Add(picSprite);
        chkShiny = new CheckBox { Text = "⭐ Shiny", Location = new Point(15, 80), Size = new Size(70, 25), Appearance = Appearance.Button, TextAlign = ContentAlignment.MiddleCenter, Cursor = Cursors.Hand }; chkShiny.CheckedChanged += ChkShiny_CheckedChanged; grpEditor.Controls.Add(chkShiny);
        chkSuperShiny = new CheckBox { Text = "🌟 Radiante", Location = new Point(88, 80), Size = new Size(82, 25), Appearance = Appearance.Button, TextAlign = ContentAlignment.MiddleCenter, Cursor = Cursors.Hand }; chkSuperShiny.CheckedChanged += ChkSuperShiny_CheckedChanged; grpEditor.Controls.Add(chkSuperShiny);
        btnInfo = new Button { Text = "Ver Info Extra", Location = new Point(175, 25), Size = new Size(200, 45), Font = new Font("Segoe UI", 10F, FontStyle.Bold) }; btnInfo.Click += BtnInfo_Click; grpEditor.Controls.Add(btnInfo);

        tabEditor = new TabControl { Location = new Point(10, 110), Size = new Size(375, 355) };
        TabPage pageGen = new TabPage("General");
        pageGen.Controls.Add(new Label { Text = "Mote:", Location = new Point(15, 20), Size = new Size(70, 20) }); txtNickname = new TextBox { Location = new Point(90, 17), Size = new Size(130, 23) }; pageGen.Controls.Add(txtNickname);
        pageGen.Controls.Add(new Label { Text = "Nivel:", Location = new Point(230, 20), Size = new Size(50, 20) }); numLevel = new NumericUpDown { Location = new Point(280, 17), Size = new Size(50, 23), Minimum = 1, Maximum = 100 }; pageGen.Controls.Add(numLevel);
        pageGen.Controls.Add(new Label { Text = "Objeto:", Location = new Point(15, 60), Size = new Size(70, 20) }); cbItem = new ComboBox { Location = new Point(90, 57), Size = new Size(240, 23), AutoCompleteMode = AutoCompleteMode.SuggestAppend, AutoCompleteSource = AutoCompleteSource.ListItems }; cbItem.TextUpdate += (s, e) => { if (cbItem.DroppedDown) cbItem.DroppedDown = false; }; pageGen.Controls.Add(cbItem);
        pageGen.Controls.Add(new Label { Text = "Habilidad:", Location = new Point(15, 100), Size = new Size(70, 20) }); cbAbility = new ComboBox { Location = new Point(90, 97), Size = new Size(130, 23), AutoCompleteMode = AutoCompleteMode.SuggestAppend, AutoCompleteSource = AutoCompleteSource.ListItems }; cbAbility.TextUpdate += (s, e) => { if (cbAbility.DroppedDown) cbAbility.DroppedDown = false; }; pageGen.Controls.Add(cbAbility);
        btnDescAbility = new Button { Text = "?", Location = new Point(223, 96), Size = new Size(23, 25) }; btnDescAbility.Click += BtnDescAbility_Click; pageGen.Controls.Add(btnDescAbility);
        Button btnAutoAbil = new Button { Text = "Auto ▼", Location = new Point(250, 96), Size = new Size(42, 25), BackColor = Color.LightYellow }; ContextMenuStrip autoMenu = new ContextMenuStrip(); autoMenu.Items.Add("Auto: Ranura 1 (Principal)").Click += (s,e) => { cbAbility.Text = "Auto: Ranura 1"; }; autoMenu.Items.Add("Auto: Ranura 2 (Secundaria)").Click += (s,e) => { cbAbility.Text = "Auto: Ranura 2"; }; autoMenu.Items.Add("Auto: Ranura 3 (Oculta)").Click += (s,e) => { cbAbility.Text = "Auto: Oculta"; }; btnAutoAbil.Click += (s, e) => { autoMenu.Show(btnAutoAbil, new Point(0, btnAutoAbil.Height)); }; pageGen.Controls.Add(btnAutoAbil);
        pageGen.Controls.Add(new Label { Text = "Naturaleza:", Location = new Point(15, 140), Size = new Size(70, 20) }); cbNature = new ComboBox { Location = new Point(90, 137), Size = new Size(240, 23), DropDownStyle = ComboBoxStyle.DropDownList }; cbNature.SelectedIndexChanged += (s, e) => { if (!isUpdatingUI) { UpdateStatColorsByNature(); } }; pageGen.Controls.Add(cbNature);
        pageGen.Controls.Add(new Label { Text = "Sexo:", Location = new Point(15, 180), Size = new Size(70, 20) }); cbGender = new ComboBox { Location = new Point(90, 177), Size = new Size(110, 23), DropDownStyle = ComboBoxStyle.DropDownList }; cbGender.Items.AddRange(new string[] { "Macho ♂", "Hembra ♀", "Sin Género ⚲" }); pageGen.Controls.Add(cbGender);
        Button btnMaxHappiness = new Button { Text = "Max Felicidad ♥", Location = new Point(210, 176), Size = new Size(120, 25), BackColor = Color.LightPink }; btnMaxHappiness.Click += BtnMaxHappiness_Click; pageGen.Controls.Add(btnMaxHappiness);
        btnChangeFormInEditor = new Button { Text = "🌀 Cambiar Forma / Paradox", Location = new Point(15, 220), Size = new Size(335, 30), BackColor = Color.Lavender, Font = new Font("Segoe UI", 9.5F, FontStyle.Bold) }; btnChangeFormInEditor.Click += ChangeForm_Click; pageGen.Controls.Add(btnChangeFormInEditor);
        tabEditor.TabPages.Add(pageGen);

        TabPage pageStats = new TabPage("Stats");
        pageStats.Controls.Add(new Label { Text = "Stat", Location = new Point(20, 15), Size = new Size(60, 20), Font = new Font(this.Font, FontStyle.Bold) }); pageStats.Controls.Add(new Label { Text = "IVs (0-31)", Location = new Point(120, 15), Size = new Size(80, 20), Font = new Font(this.Font, FontStyle.Bold) }); pageStats.Controls.Add(new Label { Text = "EVs (0-252)", Location = new Point(220, 15), Size = new Size(80, 20), Font = new Font(this.Font, FontStyle.Bold) });
        for (int i = 0; i < 6; i++) { int yPos = 40 + (i * 35); lblStatNames[i] = new Label { Text = statNames[i], Location = new Point(20, yPos + 2), Size = new Size(80, 20), Font = new Font(this.Font, FontStyle.Bold) }; pageStats.Controls.Add(lblStatNames[i]); numIVs[i] = new NumericUpDown { Location = new Point(120, yPos), Size = new Size(60, 23), Minimum = 0, Maximum = 31 }; pageStats.Controls.Add(numIVs[i]); numEVs[i] = new NumericUpDown { Location = new Point(220, yPos), Size = new Size(60, 23), Minimum = 0, Maximum = 252 }; pageStats.Controls.Add(numEVs[i]); }
        tabEditor.TabPages.Add(pageStats);

        TabPage pageMoves = new TabPage("Movimientos");
        pageMoves.Controls.Add(new Label { Text = "Ataque", Location = new Point(15, 10), Size = new Size(120, 20), Font = new Font(this.Font, FontStyle.Bold) }); pageMoves.Controls.Add(new Label { Text = "PPs", Location = new Point(200, 10), Size = new Size(50, 20), Font = new Font(this.Font, FontStyle.Bold) }); pageMoves.Controls.Add(new Label { Text = "+PP", Location = new Point(265, 10), Size = new Size(60, 20), Font = new Font(this.Font, FontStyle.Bold) });
        for (int i = 0; i < 4; i++) { int idx = i; int yPos = 35 + (i * 45); cbMoves[i] = new ComboBox { Location = new Point(15, yPos), Size = new Size(150, 23), AutoCompleteMode = AutoCompleteMode.SuggestAppend, AutoCompleteSource = AutoCompleteSource.ListItems }; cbMoves[i].TextUpdate += (s, e) => { if (cbMoves[idx].DroppedDown) cbMoves[idx].DroppedDown = false; }; cbMoves[i].SelectedIndexChanged += (s, e) => { if (!isUpdatingUI) UpdatePPLimits(idx); }; pageMoves.Controls.Add(cbMoves[i]); btnDescMoves[i] = new Button { Text = "?", Location = new Point(168, yPos - 1), Size = new Size(25, 25) }; btnDescMoves[i].Click += (s, e) => BtnDescMoves_Click(idx); pageMoves.Controls.Add(btnDescMoves[i]); numPPs[i] = new NumericUpDown { Location = new Point(200, yPos), Size = new Size(50, 23), Minimum = 0, Maximum = 99 }; pageMoves.Controls.Add(numPPs[i]); numPPUps[i] = new NumericUpDown { Location = new Point(265, yPos), Size = new Size(45, 23), Minimum = 0, Maximum = 3 }; numPPUps[i].ValueChanged += (s, e) => { if (!isUpdatingUI) UpdatePPLimits(idx); }; pageMoves.Controls.Add(numPPUps[i]); }
        btnMaxPP = new Button { Text = "Max PPs Todos", Location = new Point(15, 225), Size = new Size(335, 30), BackColor = Color.LightGreen }; btnMaxPP.Click += BtnMaxPP_Click; pageMoves.Controls.Add(btnMaxPP);
        tabEditor.TabPages.Add(pageMoves);
        
        grpEditor.Controls.Add(tabEditor);
        this.Controls.Add(grpEditor);

        lblStatus = new Label { Location = new Point(12, 540), Size = new Size(810, 20), Text = "Esperando...", ForeColor = Color.Gray };
        this.Controls.Add(lblStatus);
    }

    // --- EVENTOS DE INTERFAZ ---
    private void UniversalSlot_MouseDown(object sender, MouseEventArgs e) { if (e.Button == MouseButtons.Left) { dragStartPos = e.Location; dragSlotIndex = (int)((PictureBox)sender).Tag; isDragging = false; } }
    private void UniversalSlot_MouseMove(object sender, MouseEventArgs e) { if (e.Button == MouseButtons.Left && dragSlotIndex != -1 && !isDragging) { if (Math.Abs(e.X - dragStartPos.X) > 4 || Math.Abs(e.Y - dragStartPos.Y) > 4) { PictureBox pb = (PictureBox)sender; bool isPartySlot = pb.Parent == tabParty; if (isPartySlot) { if (currentSaveData != null && dragSlotIndex < currentSaveData.Party.Count) { isDragging = true; int slot = dragSlotIndex; dragSlotIndex = -1; pb.DoDragDrop(new DragData { IsParty = true, BoxIndex = 0, SlotIndex = slot }, DragDropEffects.Move); } } else { if (currentSaveData != null && currentSaveData.Boxes[currentBoxIndex].Slots[dragSlotIndex] != null) { isDragging = true; int slot = dragSlotIndex; dragSlotIndex = -1; pb.DoDragDrop(new DragData { IsParty = false, BoxIndex = currentBoxIndex, SlotIndex = slot }, DragDropEffects.Move); } } } } }
    private void UniversalSlot_MouseUp(object sender, MouseEventArgs e) { if (!isDragging && dragSlotIndex != -1) { PictureBox pb = (PictureBox)sender; if (pb.Parent == tabParty) PartySlot_ClickAction(sender, EventArgs.Empty); else PcSlot_ClickAction(sender, EventArgs.Empty); } dragSlotIndex = -1; isDragging = false; }
    private void UniversalSlot_DragEnter(object sender, DragEventArgs e) { if (e.Data.GetDataPresent(typeof(DragData))) e.Effect = DragDropEffects.Move; }
    private void PartySlot_ClickAction(object sender, EventArgs e) { if (isUpdatingUI) return; PictureBox clickedSlot = sender as PictureBox; if (clickedSlot == null) return; int slotIndex = (int)clickedSlot.Tag; if (currentSaveData == null || slotIndex >= currentSaveData.Party.Count) { ApplyCurrentEdits(); grpEditor.Enabled = false; currentSlotIndex = -1; return; } ApplyCurrentEdits(); isEditingParty = true; currentSlotIndex = slotIndex; LoadPokemonToEditor(); }
    private void PcSlot_ClickAction(object sender, EventArgs e) { if (isUpdatingUI) return; PictureBox clickedSlot = sender as PictureBox; if (clickedSlot == null) return; int slotIndex = (int)clickedSlot.Tag; if (currentSaveData.Boxes[currentBoxIndex].Slots[slotIndex] == null) { ApplyCurrentEdits(); grpEditor.Enabled = false; currentSlotIndex = -1; return; } ApplyCurrentEdits(); isEditingParty = false; currentSlotIndex = slotIndex; LoadPokemonToEditor(); }
    private void PartySlot_DragDrop(object sender, DragEventArgs e) { DragData source = (DragData)e.Data.GetData(typeof(DragData)); PictureBox pb = sender as PictureBox; int targetSlot = (int)pb.Tag; Unified_DragDrop(source, true, 0, targetSlot); }
    private void PcSlot_DragDrop(object sender, DragEventArgs e) { DragData source = (DragData)e.Data.GetData(typeof(DragData)); PictureBox pb = sender as PictureBox; int targetSlot = (int)pb.Tag; Unified_DragDrop(source, false, currentBoxIndex, targetSlot); }
    private void Unified_DragDrop(DragData source, bool targetIsParty, int targetBox, int targetSlot) {
        if (source.IsParty == targetIsParty && source.BoxIndex == targetBox && source.SlotIndex == targetSlot) return; lblStatus.Text = "⏳ Moviendo Pokémon..."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents();
        try {
            ApplyCurrentEdits(); SaveWriter writer = new SaveWriter(currentSavePath, currentSaveData.RootData);
            if (source.IsParty && !targetIsParty) { if (currentSaveData.Boxes[targetBox].Slots[targetSlot] != null) { writer.SwapPokemonInRuby(true, 0, source.SlotIndex, false, targetBox, targetSlot); } else { writer.ClonePokemonInRuby(true, 0, source.SlotIndex, false, targetBox, targetSlot); writer.DeletePokemonInRuby(true, 0, source.SlotIndex); } } else if (!source.IsParty && targetIsParty) { if (targetSlot < currentSaveData.Party.Count) { writer.SwapPokemonInRuby(false, source.BoxIndex, source.SlotIndex, true, 0, targetSlot); } else { if (currentSaveData.Party.Count >= 6) { MessageBox.Show("El equipo ya está lleno.", "Aviso", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } writer.ClonePokemonInRuby(false, source.BoxIndex, source.SlotIndex, true, 0, currentSaveData.Party.Count); writer.DeletePokemonInRuby(false, source.BoxIndex, source.SlotIndex); } } else if (!source.IsParty && !targetIsParty) { writer.SwapPokemonInRuby(false, source.BoxIndex, source.SlotIndex, false, targetBox, targetSlot); } else if (source.IsParty && targetIsParty) { if (targetSlot < currentSaveData.Party.Count) { writer.SwapPokemonInRuby(true, 0, source.SlotIndex, true, 0, targetSlot); } else { writer.ClonePokemonInRuby(true, 0, source.SlotIndex, true, 0, currentSaveData.Party.Count); writer.DeletePokemonInRuby(true, 0, source.SlotIndex); } }
            ReloadFromMemory(); if (isEditingParty == targetIsParty) { if (currentBoxIndex == targetBox || targetIsParty) { currentSlotIndex = targetIsParty ? Math.Min(targetSlot, currentSaveData.Party.Count - 1) : targetSlot; } } LoadPokemonToEditor(); lblStatus.Text = "Pokémon movido con éxito."; lblStatus.ForeColor = Color.Green;
        } finally { this.Cursor = Cursors.Default; }
    }
    private void MovePokemonQuick_Click(object sender, EventArgs e) { var pb = ((sender as ToolStripItem).Owner as ContextMenuStrip).SourceControl as PictureBox; if (pb == null) return; bool isParty = pb.Parent == tabParty; int slot = (int)pb.Tag; if (isParty) { int targetBox = -1, targetSlot = -1; for (int b = 0; b < currentSaveData.Boxes.Count; b++) { for (int s = 0; s < 30; s++) { if (currentSaveData.Boxes[b].Slots[s] == null) { targetBox = b; targetSlot = s; break; } } if (targetBox != -1) break; } if (targetBox == -1) { MessageBox.Show("Todas las cajas del PC están llenas.", "Aviso"); return; } Unified_DragDrop(new DragData { IsParty = true, BoxIndex = 0, SlotIndex = slot }, false, targetBox, targetSlot); } else { if (currentSaveData.Party.Count >= 6) { MessageBox.Show("El equipo ya está lleno.", "Aviso"); return; } Unified_DragDrop(new DragData { IsParty = false, BoxIndex = currentBoxIndex, SlotIndex = slot }, true, 0, currentSaveData.Party.Count); } }
    private void DeletePokemon_Click(object sender, EventArgs e) { var pb = ((sender as ToolStripItem).Owner as ContextMenuStrip).SourceControl as PictureBox; if (pb == null) return; bool isParty = pb.Parent == tabParty; int slot = (int)pb.Tag; if (MessageBox.Show("¿Eliminar de forma permanente?", "Confirmar", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes) { lblStatus.Text = "⏳ Eliminando Pokémon..."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents(); try { ApplyCurrentEdits(); SyncAllToRuby(); SaveWriter writer = new SaveWriter(currentSavePath, currentSaveData.RootData); if (isParty) writer.DeletePokemonInRuby(true, 0, slot); else writer.DeletePokemonInRuby(false, currentBoxIndex, slot); ReloadFromMemory(); grpEditor.Enabled = false; lblStatus.Text = "Pokémon eliminado."; lblStatus.ForeColor = Color.Red; } finally { this.Cursor = Cursors.Default; } } }
    private void BtnAddPokemon_Click(object sender, EventArgs e) { if (currentSaveData == null) return; int targetSlot = -1; for (int i = 0; i < 30; i++) { if (currentSaveData.Boxes[currentBoxIndex].Slots[i] == null) { targetSlot = i; break; } } if (targetSlot == -1) { MessageBox.Show("La caja actual está llena.", "Aviso", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } using (AddPokemonForm form = new AddPokemonForm(pbs)) { if (form.ShowDialog() == DialogResult.OK) { lblStatus.Text = "⏳ Generando Pokémon e inyectando en la caja..."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents(); try { ApplyCurrentEdits(); SyncAllToRuby(); SaveWriter writer = new SaveWriter(currentSavePath, currentSaveData.RootData); string intSpc = form.SelectedSpeciesInternal; string gr = pbs.SpeciesGrowthRates.ContainsKey(intSpc) ? pbs.SpeciesGrowthRates[intSpc] : "MEDIUMFAST"; int exactExp = PokemonUtils.CalculateExp(form.Level, gr); bool success = writer.AddPokemon(false, currentBoxIndex, intSpc, form.SelectedSpeciesName, form.Level, exactExp, "AUTO_0"); if (success) { ReloadFromMemory(); isEditingParty = false; currentSlotIndex = targetSlot; LoadPokemonToEditor(); lblStatus.Text = $"¡Pokémon añadido! Habilidad lista para el Modo Random."; lblStatus.ForeColor = Color.Green; } } finally { this.Cursor = Cursors.Default; } } } }
    private void BtnBoxChange_DragOver(object sender, DragEventArgs e) { if (e.Data.GetDataPresent(typeof(DragData)) && (DateTime.Now - lastBoxSwitch).TotalMilliseconds > 700) { Button btn = sender as Button; if (btn == btnNextBox && cbBoxSelector.SelectedIndex < cbBoxSelector.Items.Count - 1) cbBoxSelector.SelectedIndex++; else if (btn == btnPrevBox && cbBoxSelector.SelectedIndex > 0) cbBoxSelector.SelectedIndex--; lastBoxSwitch = DateTime.Now; } }

    private void UpdateBagItemDropdown() { if (!pbs.IsLoaded || tabBagPockets.SelectedIndex < 0) return; int currentPocket = tabBagPockets.SelectedIndex + 1; if (dgvPockets[currentPocket] == null) return; string currentSelection = cbBagItems.Text; cbBagItems.Items.Clear(); HashSet<string> existingItems = new HashSet<string>(StringComparer.OrdinalIgnoreCase); if (currentPocket == 4 || currentPocket == 8) { foreach (DataGridViewRow row in dgvPockets[currentPocket].Rows) { if (row.Cells[0].Value != null) existingItems.Add(row.Cells[0].Value.ToString()); } } foreach (var kvp in pbs.Items) { int pkt = pbs.ItemPockets.ContainsKey(kvp.Key) ? pbs.ItemPockets[kvp.Key] : 1; if (pkt == currentPocket && !existingItems.Contains(kvp.Key)) { cbBagItems.Items.Add(pbs.GetName(pbs.Items, kvp.Key, kvp.Value)); } } if (cbBagItems.Items.Contains(currentSelection)) cbBagItems.SelectedItem = currentSelection; else if (cbBagItems.Items.Count > 0) cbBagItems.SelectedIndex = 0; }
    private void BtnBagAdd_Click(object sender, EventArgs e) { if (string.IsNullOrWhiteSpace(cbBagItems.Text)) return; string intId = PokemonUtils.GetInternalId(pbs.Items, cbBagItems.Text, "", pbs); if (string.IsNullOrEmpty(intId)) return; int pocket = tabBagPockets.SelectedIndex + 1; int qtyToAdd = (pocket == 4 || pocket == 8) ? 1 : (int)numBagQty.Value; foreach (DataGridViewRow row in dgvPockets[pocket].Rows) { if (qtyToAdd <= 0) break; if (row.Cells[0].Value != null && row.Cells[0].Value.ToString().Equals(intId, StringComparison.OrdinalIgnoreCase)) { int currentQty = Convert.ToInt32(row.Cells[2].Value); int maxAllowed = (pocket == 4 || pocket == 8) ? 1 : 999; if (currentQty < maxAllowed) { int spaceAvailable = maxAllowed - currentQty; int amountToFill = Math.Min(qtyToAdd, spaceAvailable); row.Cells[2].Value = currentQty + amountToFill; qtyToAdd -= amountToFill; } else if (pocket == 4 || pocket == 8) { qtyToAdd = 0; } } } while (qtyToAdd > 0) { int maxAllowed = (pocket == 4 || pocket == 8) ? 1 : 999; int amountForNewSlot = Math.Min(qtyToAdd, maxAllowed); dgvPockets[pocket].Rows.Add(intId, cbBagItems.Text, amountForNewSlot); qtyToAdd -= amountForNewSlot; if (pocket == 4 || pocket == 8) break; } UpdateBagItemDropdown(); }
    private void BtnBagMaxSelected_Click(object sender, EventArgs e) { if (tabBagPockets.SelectedIndex < 0) return; int pocket = tabBagPockets.SelectedIndex + 1; if (pocket == 4 || pocket == 8) { MessageBox.Show("Las MTs y Objetos Clave no pueden tener más de 1 unidad.", "Aviso", MessageBoxButtons.OK, MessageBoxIcon.Information); return; } if (dgvPockets[pocket].SelectedRows.Count > 0) { foreach (DataGridViewRow row in dgvPockets[pocket].SelectedRows) { if (!row.IsNewRow) row.Cells[2].Value = 999; } UpdateBagItemDropdown(); } else { MessageBox.Show("Selecciona un objeto de la tabla haciendo clic en su fila.", "Aviso", MessageBoxButtons.OK, MessageBoxIcon.Warning); } }
    private void BtnBagMaxCurrent_Click(object sender, EventArgs e) { if (currentSaveData == null) return; lblStatus.Text = "⏳ Maximizando los objetos que ya tienes..."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents(); try { for (int pId = 1; pId <= 8; pId++) { if (dgvPockets[pId] == null) continue; int targetQty = (pId == 4 || pId == 8) ? 1 : 999; foreach (DataGridViewRow row in dgvPockets[pId].Rows) { if (row.Cells[0].Value != null) row.Cells[2].Value = targetQty; } } UpdateBagItemDropdown(); lblStatus.Text = "¡Tus objetos actuales han sido maximizados a 999!"; lblStatus.ForeColor = Color.Green; } finally { this.Cursor = Cursors.Default; } }
    private void BtnBagAddAll_Click(object sender, EventArgs e) { if (!pbs.IsLoaded) return; lblStatus.Text = "⏳ Inyectando todos los objetos del juego... Esto puede tardar unos segundos."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents(); try { foreach (var kvp in pbs.Items) { string intId = kvp.Key; string realName = pbs.GetName(pbs.Items, intId, kvp.Value); int pkt = pbs.ItemPockets.ContainsKey(intId) ? pbs.ItemPockets[intId] : 1; int targetQty = (pkt == 4 || pkt == 8) ? 1 : 999; bool found = false; foreach (DataGridViewRow row in dgvPockets[pkt].Rows) { if (row.Cells[0].Value != null && row.Cells[0].Value.ToString().Equals(intId, StringComparison.OrdinalIgnoreCase)) { found = true; if (pkt != 4 && pkt != 8) row.Cells[2].Value = targetQty; break; } } if (!found) dgvPockets[pkt].Rows.Add(intId, realName, targetQty); } UpdateBagItemDropdown(); lblStatus.Text = "¡Todos los objetos del juego han sido añadidos a tu mochila!"; lblStatus.ForeColor = Color.Green; } finally { this.Cursor = Cursors.Default; } }
    private void BtnBagRemove_Click(object sender, EventArgs e) { if (tabBagPockets.SelectedIndex < 0) return; int pocket = tabBagPockets.SelectedIndex + 1; if (dgvPockets[pocket].SelectedRows.Count > 0) { foreach (DataGridViewRow row in dgvPockets[pocket].SelectedRows) { if (!row.IsNewRow) dgvPockets[pocket].Rows.Remove(row); } UpdateBagItemDropdown(); } else { MessageBox.Show("Por favor, selecciona primero una fila en la tabla de arriba para borrarla.", "Borrar Objeto", MessageBoxButtons.OK, MessageBoxIcon.Information); } }

    private void ChkShiny_CheckedChanged(object sender, EventArgs e) { if (isUpdatingUI) return; chkShiny.BackColor = chkShiny.Checked ? Color.Gold : SystemColors.Control; if (chkShiny.Checked && chkSuperShiny.Checked) { isUpdatingUI = true; chkSuperShiny.Checked = false; chkSuperShiny.BackColor = SystemColors.Control; isUpdatingUI = false; } ApplyCurrentEdits(); LoadSpriteOnly(); }
    private void ChkSuperShiny_CheckedChanged(object sender, EventArgs e) { if (isUpdatingUI) return; chkSuperShiny.BackColor = chkSuperShiny.Checked ? Color.Plum : SystemColors.Control; if (chkSuperShiny.Checked && chkShiny.Checked) { isUpdatingUI = true; chkShiny.Checked = false; chkShiny.BackColor = SystemColors.Control; isUpdatingUI = false; } ApplyCurrentEdits(); LoadSpriteOnly(); }
    private void BtnDescAbility_Click(object sender, EventArgs e) { string internalId = PokemonUtils.GetInternalId(pbs.Abilities, cbAbility.Text, "", pbs); string desc = pbs.AbilityDescriptions.TryGetValue(internalId, out string d) ? d : "Sin descripción disponible."; MessageBox.Show(desc, $"Habilidad: {cbAbility.Text}", MessageBoxButtons.OK, MessageBoxIcon.Information); }
    private void BtnMaxHappiness_Click(object sender, EventArgs e) { Pokemon p = GetCurrentPokemon(); if (p != null) { p.Happiness = 255; lblStatus.Text = $"¡Felicidad de {p.Nickname} al máximo (255)!"; lblStatus.ForeColor = Color.DeepPink; } }
    private void BtnDescMoves_Click(int idx) { string internalId = PokemonUtils.GetInternalId(pbs.Moves, cbMoves[idx].Text, "", pbs); string desc = pbs.MoveDescriptions.TryGetValue(internalId, out string d) ? d : "Sin descripción disponible."; MessageBox.Show(desc, $"Movimiento: {cbMoves[idx].Text}", MessageBoxButtons.OK, MessageBoxIcon.Information); }
    private void BtnMaxPP_Click(object sender, EventArgs e) { for (int i = 0; i < 4; i++) { if (cbMoves[i].Enabled && !string.IsNullOrWhiteSpace(cbMoves[i].Text)) { numPPUps[i].Value = 3; numPPs[i].Value = numPPs[i].Maximum; } } }
    private void BtnInfo_Click(object sender, EventArgs e) { ApplyCurrentEdits(); Pokemon p = GetCurrentPokemon(); if (p == null) return; InfoForm infoWindow = new InfoForm(p, picSprite.Image, pbs); infoWindow.ShowDialog(); }
    private void ChangeForm_Click(object sender, EventArgs e) { var pb = ((sender as ToolStripItem).Owner as ContextMenuStrip)?.SourceControl as PictureBox; if (pb == null && sender is Button) pb = partySlots[currentSlotIndex]; if (pb == null) return; bool isParty = pb.Parent == tabParty || (sender is Button && isEditingParty); int slot = (sender is Button) ? currentSlotIndex : (int)pb.Tag; if (currentSaveData == null) return; Pokemon p = isParty ? (slot < currentSaveData.Party.Count ? currentSaveData.Party[slot] : null) : currentSaveData.Boxes[currentBoxIndex].Slots[slot]; if (p == null) return; using (ChangeFormDialog formDialog = new ChangeFormDialog(pbs, p)) { if (formDialog.ShowDialog() == DialogResult.OK) { lblStatus.Text = "⏳ Aplicando transformación y guardando..."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents(); try { ApplyCurrentEdits(); p.Form = formDialog.SelectedForm; if (!string.IsNullOrEmpty(formDialog.SelectedSpeciesInternal)) { p.InternalSpecies = formDialog.SelectedSpeciesInternal; p.Species = pbs.GetName(pbs.Species, p.InternalSpecies, p.InternalSpecies); } p.InternalAbility = "AUTO_0"; p.Ability = "Auto: Ranura 1"; p.Nickname = p.Species; SyncAllToRuby(); ReloadFromMemory(); lblStatus.Text = $"Forma de {p.Nickname} actualizada correctamente."; lblStatus.ForeColor = Color.DarkViolet; } finally { this.Cursor = Cursors.Default; } } } }

    private void RefreshPartyGrid() { if (currentSaveData == null) return; for (int i = 0; i < 6; i++) { if (partySlots[i].Image != null) partySlots[i].Image.Dispose(); partySlots[i].Image = null; if (i < currentSaveData.Party.Count) { Pokemon p = currentSaveData.Party[i]; partySlots[i].BackColor = Color.LightCyan; partySlots[i].Image = SpriteManager.GetPokemonIcon(AppRoot, p.InternalSpecies, p.Form, p.IsShiny || p.IsSuperShiny); partyLabels[i].Text = $"{p.Nickname}\nNv. {p.Level}"; partyLabels[i].ForeColor = Color.Black; } else { partySlots[i].BackColor = Color.WhiteSmoke; partyLabels[i].Text = "Vacío"; partyLabels[i].ForeColor = Color.Gray; } } }
    private void RefreshPCGrid() { if (currentSaveData == null || currentBoxIndex < 0 || currentBoxIndex >= currentSaveData.Boxes.Count) return; var box = currentSaveData.Boxes[currentBoxIndex]; for (int i = 0; i < 30; i++) { Pokemon p = box.Slots[i]; if (pcSlots[i].Image != null) pcSlots[i].Image.Dispose(); pcSlots[i].Image = null; pcSlots[i].BackColor = (p != null) ? Color.LightCyan : Color.WhiteSmoke; if (p != null) pcSlots[i].Image = SpriteManager.GetPokemonIcon(AppRoot, p.InternalSpecies, p.Form, p.IsShiny || p.IsSuperShiny); } }
    private void UpdateStatColorsByNature() { string selectedText = cbNature.Text; string intNat = PokemonUtils.GetInternalIdFromNatureText(selectedText, pbs); for (int i = 0; i < 6; i++) lblStatNames[i].ForeColor = Color.Black; switch (intNat?.ToUpper()) { case "LONELY": lblStatNames[1].ForeColor = Color.Red; lblStatNames[2].ForeColor = Color.Blue; break; case "BRAVE":  lblStatNames[1].ForeColor = Color.Red; lblStatNames[5].ForeColor = Color.Blue; break; case "ADAMANT":lblStatNames[1].ForeColor = Color.Red; lblStatNames[3].ForeColor = Color.Blue; break; case "NAUGHTY":lblStatNames[1].ForeColor = Color.Red; lblStatNames[4].ForeColor = Color.Blue; break; case "BOLD":   lblStatNames[2].ForeColor = Color.Red; lblStatNames[1].ForeColor = Color.Blue; break; case "RELAXED":lblStatNames[2].ForeColor = Color.Red; lblStatNames[5].ForeColor = Color.Blue; break; case "IMPISH": lblStatNames[2].ForeColor = Color.Red; lblStatNames[3].ForeColor = Color.Blue; break; case "LAX":    lblStatNames[2].ForeColor = Color.Red; lblStatNames[4].ForeColor = Color.Blue; break; case "MODEST": lblStatNames[3].ForeColor = Color.Red; lblStatNames[1].ForeColor = Color.Blue; break; case "MILD":   lblStatNames[3].ForeColor = Color.Red; lblStatNames[2].ForeColor = Color.Blue; break; case "QUIET":  lblStatNames[3].ForeColor = Color.Red; lblStatNames[5].ForeColor = Color.Blue; break; case "RASH":   lblStatNames[3].ForeColor = Color.Red; lblStatNames[4].ForeColor = Color.Blue; break; case "CALM":   lblStatNames[4].ForeColor = Color.Red; lblStatNames[1].ForeColor = Color.Blue; break; case "GENTLE": lblStatNames[4].ForeColor = Color.Red; lblStatNames[2].ForeColor = Color.Blue; break; case "SASSY":  lblStatNames[4].ForeColor = Color.Red; lblStatNames[5].ForeColor = Color.Blue; break; case "CAREFUL":lblStatNames[4].ForeColor = Color.Red; lblStatNames[3].ForeColor = Color.Blue; break; case "TIMID":  lblStatNames[5].ForeColor = Color.Red; lblStatNames[1].ForeColor = Color.Blue; break; case "HASTY":  lblStatNames[5].ForeColor = Color.Red; lblStatNames[2].ForeColor = Color.Blue; break; case "JOLLY":  lblStatNames[5].ForeColor = Color.Red; lblStatNames[3].ForeColor = Color.Blue; break; case "NAIVE":  lblStatNames[5].ForeColor = Color.Red; lblStatNames[4].ForeColor = Color.Blue; break; } }
    private void UpdatePPLimits(int moveIndex) { string moveName = cbMoves[moveIndex].Text; string internalId = PokemonUtils.GetInternalId(pbs.Moves, moveName, "", pbs); int basePP = 10; if (pbs.MovePPs.TryGetValue(internalId, out int pp)) basePP = pp; int ppUps = (int)numPPUps[moveIndex].Value; int maxPP = basePP + (basePP * ppUps / 5); numPPs[moveIndex].Maximum = Math.Max(1, maxPP); if (numPPs[moveIndex].Value > numPPs[moveIndex].Maximum) numPPs[moveIndex].Value = numPPs[moveIndex].Maximum; }

    private void ApplyCurrentEdits() {
        if (isUpdatingUI) return; Pokemon p = GetCurrentPokemon(); if (p == null) return;
        try {
            isUpdatingUI = true; p.Nickname = txtNickname.Text; p.Level = (int)numLevel.Value; string gr = pbs.SpeciesGrowthRates.ContainsKey(p.InternalSpecies) ? pbs.SpeciesGrowthRates[p.InternalSpecies] : "MEDIUMFAST"; p.Exp = PokemonUtils.CalculateExp(p.Level, gr); p.IsShiny = chkShiny.Checked; p.IsSuperShiny = chkSuperShiny.Checked; p.Gender = cbGender.Text; p.HeldItem = cbItem.Text; p.InternalHeldItem = PokemonUtils.GetInternalId(pbs.Items, cbItem.Text, p.InternalHeldItem, pbs); if (string.IsNullOrWhiteSpace(p.InternalHeldItem)) p.InternalHeldItem = "Ninguno"; p.Nature = PokemonUtils.GetInternalIdFromNatureText(cbNature.Text, pbs); p.InternalNature = PokemonUtils.GetInternalIdFromNatureText(cbNature.Text, pbs); if (cbAbility.Text == "Auto: Ranura 1") { p.Ability = "Auto: Ranura 1"; p.InternalAbility = "AUTO_0"; } else if (cbAbility.Text == "Auto: Ranura 2") { p.Ability = "Auto: Ranura 2"; p.InternalAbility = "AUTO_1"; } else if (cbAbility.Text == "Auto: Oculta") { p.Ability = "Auto: Oculta"; p.InternalAbility = "AUTO_2"; } else { p.Ability = cbAbility.Text; p.InternalAbility = PokemonUtils.GetInternalId(pbs.Abilities, cbAbility.Text, p.InternalAbility, pbs); } for (int i = 0; i < 6; i++) { p.IVs[i] = (int)numIVs[i].Value; p.EVs[i] = (int)numEVs[i].Value; } p.Moves.Clear(); for (int i = 0; i < 4; i++) { if (!string.IsNullOrWhiteSpace(cbMoves[i].Text)) { p.Moves.Add(new PokemonMove { Name = cbMoves[i].Text, InternalName = PokemonUtils.GetInternalId(pbs.Moves, cbMoves[i].Text, "", pbs), PP = (int)numPPs[i].Value, PPUp = (int)numPPUps[i].Value }); } }
            if (isEditingParty) RefreshPartyGrid(); else RefreshPCGrid();
        } catch (Exception ex) { LogError(ex, "ApplyCurrentEdits"); } finally { isUpdatingUI = false; }
    }

    private void BtnLoad_Click(object sender, EventArgs e) { string appDataRoaming = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData); string[] possibleFolders = { Path.Combine(appDataRoaming, "Pokemon Anil"), Path.Combine(appDataRoaming, "Pokémon Añil"), Path.Combine(appDataRoaming, "PokemonAnil") }; string initialDir = possibleFolders.FirstOrDefault(Directory.Exists) ?? appDataRoaming; using (OpenFileDialog ofd = new OpenFileDialog { Title = "Seleccionar Partida (.rxdata)", Filter = "Partidas (*.rxdata)|*.rxdata|Todos (*.*)|*.*", InitialDirectory = initialDir, RestoreDirectory = true }) { if (ofd.ShowDialog() == DialogResult.OK) { currentSavePath = ofd.FileName; LoadSaveFile(); } } }

    private void LoadSaveFile() {
        lblStatus.Text = "⏳ Cargando partida y leyendo base de datos... ¡Un momento!"; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents();
        try {
            SaveParser parser = new SaveParser(currentSavePath, pbs); currentSaveData = parser.ParseSave(); isUpdatingUI = true; 
            cbBoxSelector.Items.Clear(); foreach (var box in currentSaveData.Boxes) cbBoxSelector.Items.Add($"{box.Name} (Caja {box.BoxIndex})"); 
            foreach (var grid in dgvPockets) grid?.Rows.Clear(); 
            foreach (var item in currentSaveData.Bag) { int pId = item.Pocket >= 1 && item.Pocket <= 8 ? item.Pocket : 1; string realName = pbs != null ? pbs.GetName(pbs.Items, item.InternalName, item.Name) : item.Name; dgvPockets[pId]?.Rows.Add(item.InternalName, realName, item.Quantity); }
            
            SaveWriter tempWriter = new SaveWriter(currentSavePath, currentSaveData.RootData);
            numMoney.Value = Math.Min(numMoney.Maximum, Math.Max(0m, (decimal)tempWriter.GetMoney()));

            if (pbs.IsLoaded) { cbNature.Items.Clear(); foreach (var natKvp in pbs.Natures) { string disp = PokemonUtils.GetNatureDisplayName(natKvp.Value, natKvp.Key); if (!cbNature.Items.Contains(disp)) cbNature.Items.Add(disp); } cbAbility.Items.Clear(); cbAbility.Items.AddRange(pbs.Abilities.Values.Distinct().ToArray()); cbItem.Items.Clear(); var allItemsList = pbs.Items.Select(x => pbs.GetName(pbs.Items, x.Key, x.Value)).Distinct().ToArray(); cbItem.Items.AddRange(allItemsList); var allMoves = pbs.Moves.Values.Distinct().ToArray(); foreach (var cb in cbMoves) { cb.Items.Clear(); cb.Items.AddRange(allMoves); } }
            isUpdatingUI = false; if (cbBoxSelector.Items.Count > 0) cbBoxSelector.SelectedIndex = 0; 
            RefreshPartyGrid(); RefreshPCGrid(); tabBagPockets.SelectedIndex = 0; UpdateBagItemDropdown();
            btnSave.Enabled = true; lblStatus.Text = $"Partida cargada: {Path.GetFileName(currentSavePath)}"; lblStatus.ForeColor = Color.Green;
        } catch (Exception ex) { lblStatus.Text = $"Error al cargar. Revisa errorlog.txt"; lblStatus.ForeColor = Color.Red; btnSave.Enabled = false; LogError(ex, "LoadSaveFile"); } finally { this.Cursor = Cursors.Default; }
    }

    private void CbBoxSelector_SelectedIndexChanged(object sender, EventArgs e) { if (isUpdatingUI || cbBoxSelector.SelectedIndex < 0 || currentSaveData == null) return; currentBoxIndex = cbBoxSelector.SelectedIndex; RefreshPCGrid(); }
    private Pokemon GetCurrentPokemon() { if (currentSaveData == null || currentSlotIndex < 0) return null; if (isEditingParty && currentSlotIndex < currentSaveData.Party.Count) return currentSaveData.Party[currentSlotIndex]; if (!isEditingParty && currentSlotIndex < 30) return currentSaveData.Boxes[currentBoxIndex].Slots[currentSlotIndex]; return null; }
    
    private void LoadPokemonToEditor() {
        Pokemon p = GetCurrentPokemon(); if (p == null) return; isUpdatingUI = true;
        btnChangeFormInEditor.Visible = FormDatabase.HasFormsOrParadox(p.InternalSpecies, AppRoot); txtNickname.Text = p.Nickname; numLevel.Value = Math.Min(100, Math.Max(1, p.Level)); chkShiny.Checked = p.IsShiny; chkSuperShiny.Checked = p.IsSuperShiny; chkShiny.BackColor = p.IsShiny ? Color.Gold : SystemColors.Control; chkSuperShiny.BackColor = p.IsSuperShiny ? Color.Plum : SystemColors.Control; if (cbGender.Items.Contains(p.Gender)) cbGender.SelectedItem = p.Gender; else cbGender.SelectedIndex = 0; string natDisp = PokemonUtils.GetNatureDisplayName(p.Nature, p.InternalNature); if (cbNature.Items.Contains(natDisp)) cbNature.SelectedItem = natDisp; else cbNature.Text = natDisp; UpdateStatColorsByNature(); string realItemName = pbs.GetName(pbs.Items, p.InternalHeldItem, p.HeldItem); if (cbItem.Items.Contains(realItemName)) cbItem.SelectedItem = realItemName; else cbItem.Text = realItemName; if (p.InternalAbility == "AUTO_0" || p.InternalAbility == "AUTO") { cbAbility.Text = "Auto: Ranura 1"; } else if (p.InternalAbility == "AUTO_1") { cbAbility.Text = "Auto: Ranura 2"; } else if (p.InternalAbility == "AUTO_2") { cbAbility.Text = "Auto: Oculta"; } else { if (cbAbility.Items.Contains(p.Ability)) cbAbility.SelectedItem = p.Ability; else cbAbility.Text = p.Ability; } for (int i = 0; i < 6; i++) { numIVs[i].Value = Math.Min(31, Math.Max(0, p.IVs[i])); numEVs[i].Value = Math.Min(252, Math.Max(0, p.EVs[i])); } for (int i = 0; i < 4; i++) { cbMoves[i].Enabled = numPPs[i].Enabled = numPPUps[i].Enabled = btnDescMoves[i].Enabled = true; if (i < p.Moves.Count) { if (cbMoves[i].Items.Contains(p.Moves[i].Name)) cbMoves[i].SelectedItem = p.Moves[i].Name; else cbMoves[i].Text = p.Moves[i].Name; numPPUps[i].Value = p.Moves[i].PPUp; int bp = 10; if (pbs.MovePPs.TryGetValue(PokemonUtils.GetInternalId(pbs.Moves, cbMoves[i].Text, "", pbs), out int pp)) bp = pp; int maxP = bp + (bp * (int)numPPUps[i].Value / 5); numPPs[i].Maximum = Math.Max(1, maxP); numPPs[i].Value = Math.Min(numPPs[i].Maximum, p.Moves[i].PP); } else { cbMoves[i].SelectedIndex = -1; cbMoves[i].Text = ""; numPPs[i].Value = numPPUps[i].Value = 0; } } isUpdatingUI = false; LoadSpriteOnly(); grpEditor.Enabled = true;
    }

    private void LoadSpriteOnly() { Pokemon p = GetCurrentPokemon(); if (p == null) return; if (picSprite.Image != null) picSprite.Image.Dispose(); picSprite.Image = SpriteManager.GetPokemonIcon(AppRoot, p.InternalSpecies, p.Form, chkShiny.Checked || chkSuperShiny.Checked); }

    private void BtnSave_Click(object sender, EventArgs e) {
        if (currentSaveData == null || string.IsNullOrEmpty(currentSavePath)) return;
        lblStatus.Text = "⏳ Inyectando cambios en la partida... No cierres la ventana."; lblStatus.ForeColor = Color.DarkOrange; this.Cursor = Cursors.WaitCursor; Application.DoEvents();
        try {
            ApplyCurrentEdits(); currentSaveData.Bag.Clear();
            for (int pId = 1; pId <= 8; pId++) { foreach (DataGridViewRow row in dgvPockets[pId].Rows) { if (row.Cells[0].Value != null) { currentSaveData.Bag.Add(new ItemSlot { InternalName = row.Cells[0].Value.ToString(), Name = row.Cells[1].Value.ToString(), Quantity = Convert.ToInt32(row.Cells[2].Value), Pocket = pId }); } } }
            SyncAllToRuby(); SaveWriter writer = new SaveWriter(currentSavePath, currentSaveData.RootData); writer.SyncBag(currentSaveData.Bag); writer.SyncMoney((long)numMoney.Value);
            if (writer.Save()) { lblStatus.Text = "¡Partida guardada correctamente! Se han inyectado todas las modificaciones."; lblStatus.ForeColor = Color.Blue; }
        } catch (Exception ex) { lblStatus.Text = $"Error crítico al guardar. Revisa errorlog.txt"; lblStatus.ForeColor = Color.Red; LogError(ex, "BtnSave_Click"); } finally { this.Cursor = Cursors.Default; }
    }

    private void SyncAllToRuby() { SaveWriter writer = new SaveWriter(currentSavePath, currentSaveData.RootData); for (int i = 0; i < currentSaveData.Party.Count; i++) writer.SyncPokemon(currentSaveData.Party[i], true, 0, i); foreach (var box in currentSaveData.Boxes) for (int i = 0; i < 30; i++) if (box.Slots[i] != null) writer.SyncPokemon(box.Slots[i], false, box.BoxIndex - 1, i); }
    private void ReloadFromMemory() { isUpdatingUI = true; SaveParser parser = new SaveParser(currentSavePath, pbs); currentSaveData = parser.ParseSave(currentSaveData.RootData); isUpdatingUI = false; RefreshPartyGrid(); RefreshPCGrid(); LoadPokemonToEditor(); }
    private void LogError(Exception ex, string context = "") { try { using (StreamWriter sw = new StreamWriter(Path.Combine(AppRoot, "errorlog.txt"), true)) sw.WriteLine($"[{DateTime.Now:yyyy-MM-dd HH:mm:ss}] ERROR: {context}\n{ex.ToString()}\n{new string('-', 50)}"); } catch { } }
}